### ISSUE TITLE
upstream systemd 233 compatibility

### ISSUE THREAD

**Issue by j1r1k** [eworm-de/mkinitcpio-ykfde#18]
Is there a way to make the ykfde running with upstream systemd 233-6 that is currently in Fedora 26?

I have tried with 0.6.4 and 0.7.1 without any luck (failing with `keyctl_set_timeout() failed: Permission denied`)

**Comment by eworm-de** [comment]
Possibly version `0.7.0` works, but very limited: You can not use second factor and it can not inject the passphrase to cryptsetup. You have to wait for the "Please enter passphrase for disk..." before inserting the key.

The proper way is to use `systemd` which includes https://github.com/systemd/systemd/commit/b1edf4456eabc5951d76b96bc7df2db3feebe669 and https://github.com/systemd/systemd/pull/6832/commits/0b1f68ac8731bdc6d092aa41c6d3d6c130f22248. Will Fedora 27 ship with systemd v235?

**Comment by eworm-de** [comment]
Scratch what I said about key insertion... The injection *shoud* work.
