### ISSUE TITLE
ykfde results in error: Failed opening challenge file for reading: No such file or directory

### ISSUE THREAD

**Issue by szquadri** [eworm-de/mkinitcpio-ykfde#19]
Trying to run//use on Fedora 26. After installation and configuring /etc/ykfde.conf 
When running ykfde; it is resulting in error:
```
Failed requesting key. That's ok if you do not use
second factor. Give it manually if required.
Failed opening challenge file for reading: No such file or directory
```
Not using second factor. Yubikey is properly configured for HMAC-SHA1 but requires user input (touch).
When ykfde is run it is able to access Yubikey as the light starts blinking and after touching it the error is displayed.

**Comment by eworm-de** [comment]
This assumes that you use

- an empty LUKS slot, a new challenge is generated and written to file when you run `ykfde`

or

- a used LUKS slot, a matching challenge files is required

So I guess your configuration points to a LUKS slot that was not initialized by `ykfde`. Verify that you do not use this slot, kill it and try again. Or just use another slot.
