### ISSUE TITLE
Current master segfaults in ykfde.c

### ISSUE THREAD

**Issue by rtfm3514** [eworm-de/mkinitcpio-ykfde#23]
Hi,

the current master is segfaulting for me. I bisected the first bad commit to be 76b1338 and compiling with debug symbols gives me what I think is a NULL pointer dereference at line 321 in ykfde.c:

Thread 1 "ykfde" received signal SIGSEGV, Segmentation fault.
main (argc=<optimized out>, argv=<optimized out>) at ykfde.c:321
321             len = strlen(tmp);
(gdb) print tmp
$1 = 0x0

**Comment by eworm-de** [comment]
Can you check with b40e86039521736575be726992380bf1079e34e9 applied?

**Comment by rtfm3514** [comment]
Seems fixed, also tried with cryptsetup + yubikey. I am not using second factor btw.

Thanks a lot for the speedy fix.

**Comment by eworm-de** [comment]
You are welcome. Thanks for the perfectly detailed report!
