### ISSUE TITLE
Can not Find /etc/crypttab.initramfs Antergos

### ISSUE THREAD

**Issue by jmcgrath207** [eworm-de/mkinitcpio-ykfde#26]
Hi Eworm,

First, thank you for creating this library.

I am following the Guide to Set this up on Arch 
https://github.com/eworm-de/mkinitcpio-ykfde/blob/master/README-mkinitcpio.md

 I can not find the /etc/crypttab.initramfs file. I do have mkinitcpio installed but I am also assuming that systemd initramfs service is part of it, however, I can't find the service unit itself. I also believe that when I installed Antergos and selected the LUKS options it may have done a nonstandard implementation of this but the prompt for the encrypted volume still works.

**Comment by eworm-de** [comment]
If Antergos uses `mkinitcpio` from Arch this should work with just creating the file...

Here is some info about `sd-encrypt` hook:
https://wiki.archlinux.org/index.php/dm-crypt/System_configuration#Using_sd-encrypt_hook
