### ISSUE TITLE
ykfde.service not available during boot - Fedora 30

### ISSUE THREAD

**Issue by MJ-LAMARC** [eworm-de/mkinitcpio-ykfde#28]
Hi,
I'm using Fedora 30 and applied the dracut recipe. But It won't decrypt, with or without 2nd factor, at early cryptsetup stage. And I can't see any yk* file in initramfs.
Did the procedure change for Fedora 30?

**Comment by bpereto** [comment]
Hi,
switched to arch some time ago :)

I installed a fedora 30 vm and try to reproduce there, but the usb-direction of the yubikey doesn't work at the moment..

Acording to the docs I have builded the source and installed them. One thing the docs doesn't mention is, that sudo is required, so you have to execute `make MD=markdown_py` and `sudo make install-dracut`. I assume you have done that.   

After `dracut -f` the files are showing up in the initram:   
```
sudo lsinitrd /boot/initramfs-5.0.9-301.fc30.x86_64.img  | grep ykfde
ykfde
-rw-r--r--   1 root     root         1022 Feb 14  2019 etc/udev/rules.d/20-ykfde.rules
-rw-r--r--   1 root     root          835 Feb 14  2019 etc/ykfde.conf
lrwxrwxrwx   1 root     root           19 Feb 14  2019 usr/lib/systemd/system/sysinit.target.wants/ykfde-2f.service -> ../ykfde-2f.service
lrwxrwxrwx   1 root     root           23 Feb 14  2019 usr/lib/systemd/system/sysinit.target.wants/ykfde-worker.service -> ../ykfde-worker.service
-rw-r--r--   1 root     root          587 Feb 14  2019 usr/lib/systemd/system/ykfde-2f.service
-rw-r--r--   1 root     root          405 Feb 14  2019 usr/lib/systemd/system/ykfde-worker.service
drwxr-xr-x   2 root     root            0 Feb 14  2019 usr/lib/ykfde
-rwxr-xr-x   1 root     root        21000 Feb 14  2019 usr/lib/ykfde/worker
-rwxr-xr-x   1 root     root           50 Feb 14  2019 usr/sbin/ykfde.sh
```

**Comment by MJ-LAMARC** [comment]
Re-did everything, and after the make install-dracut everything is fine. Thanks for the hint

**Comment by eworm-de** [comment]
> switched to arch some time ago :)

Good move. ;)

> Acording to the docs I have builded the source and installed them. One thing the docs doesn't mention is, that sudo is required, so you have to execute `make MD=markdown_py` and `sudo make install-dracut`. I assume you have done that.

It does. The doc has:

> Keep in mind that you need `root` privileges for installation, so switch user or prepend the last command with `sudo`.
