### ISSUE TITLE
Is it possible to (re)enable numlock for entering the PIN?

### ISSUE THREAD

**Issue by perceival** [eworm-de/mkinitcpio-ykfde#35]
While docked I have noticed my laptop BIOS setting regarding numlock state is being overwritten during grub2 boot. Is there a way:
- to preserve original numlock status?
- or to configure it separately for the screen prompting for LUKS PIN?
(dracut/Fedora)

**Comment by eworm-de** [comment]
All I do is to ask for a password with `systemd-ask-password` for second factor... I do not have any influence on numlock status here.

As this is a BIOS/UEFI default you should check if there is a setting regarding numlock.
Other than that use your preferred search engine and look for `systemd`, `numlock` & `bootup` or similar.
