### ISSUE TITLE
Grub initrd injection doesn't work on Fedora

### ISSUE THREAD

**Issue by Diniboy1123** [eworm-de/mkinitcpio-ykfde#37]
Hi,

First of all, thanks for the project, it looks incredibly promising! However I had some issues setting this up on a fresh Fedora 35 installation. You mention the need to edit /etc/default/grub with the following line:

```
GRUB_EARLY_INITRD_LINUX_CUSTOM="ykfde-challenges.img"
```

However Fedora uses grub2 and it seems to ignore this line. Due to dracut there is no support for initramfs-tools' hooks either, so I am unsure where to put this to survive updates.

**Comment by Diniboy1123** [comment]
Nvm, I had a different issue. Seemingly grub2 just adds a line to grubenv and it still works that way. However you cannot use this project to do a full system encryption. That'd be worth noting. /etc needs to be readable and writable at the time of mounting the encrypted disk.

**Comment by eworm-de** [comment]
Sure you can use this for full disk encryption, I do. The challenges are available in initramfs via extra image.

Updating the encryption keys and challenges happens later, at regular system boot.
