### ISSUE TITLE
Feature request: BIO support

### ISSUE THREAD

**Issue by perceival** [eworm-de/mkinitcpio-ykfde#39]
Not sure if that is going to be at all possible but can ykfde work with Yubikey BIO?

**Comment by eworm-de** [comment]
The Yubikey BIO does support challenge/response mode, no? No idea if it is possible to associate that with a fingerprint. I do not own a Yubikey BIO.

**Comment by perceival** [comment]
Christian,Based on what I was able to quickly find out it does not hence no luck here.Regards,KamilTemat: Re: [eworm-de/mkinitcpio-ykfde] Feature request: BIO support (Issue #39)Data: 2022-07-31 9:42Nadawca: "Christian Hesse" ***@***.***&gt;Adresat: "eworm-de/mkinitcpio-ykfde" ***@***.***&gt;; DW: "perceival" ***@***.***&gt;; "Author" ***@***.***&gt;; 

The Yubikey BIO does support challenge/response mode, no? No idea if it is possible to associate that with a fingerprint. I do not own a Yubikey BIO.

**Comment by eworm-de** [comment]
This is the feature chart:
https://www.yubico.com/de/store/compare/

No idea if any of these indicates challenge/response support. If the Yubikey BIO does not support it... No, you can not use it.
