### ISSUE TITLE
How to add /boot/ykfde-challenges.img to mkinitcpio UKI?

### ISSUE THREAD

**Issue by gustafla** [eworm-de/mkinitcpio-ykfde#41]
Hi and sorry to abuse issues for my problem solving but I'm getting tired of not finding a solution.

I'm using mkinitcpio to generate an unified kernel image as described here https://wiki.archlinux.org/title/Unified_kernel_image, but I don't see a way to include ykfde-challenges.img

I tried adding it as a "microcode" but the resulting image is not recognized by systemd-boot. I will keep trying to solve this UKI problem but if anyone happens to know the solutuon, I'd appreciate to hear it.

**Comment by gustafla** [comment]
This issue turned out to be caused by my mistake, I wrote ".img" instead of ".efi" thus causing systemd-boot to not recognize the uki. Including challenges as "microcode" works!

**Comment by spjz** [comment]
Note that using `ALL_microcode` is deprecated. Instead you should add the `ykfde-challenges.img` to `Initrd=..` in `/etc/ukify.conf` (or however you are generating your UKI). See https://wiki.archlinux.org/title/Unified_kernel_image
