### ISSUE TITLE
unrecognized option '--keyname=ykfde-2f'

### ISSUE THREAD

**Issue by bpereto** [eworm-de/mkinitcpio-ykfde#6]
Tried out your newest commits to ykfde 2f.

Unfortunately it breaks my Installation on Fedora with this line in journald:
ykfde-2f[219]: systemd-ask-password: unrecognized option '--keyname=ykfde-2f'

the option --keyname shows up with Systemd v227
https://github.com/systemd/systemd/commit/e287086b8aa2558356af225a12d9bfea8e7d61ca

Fedora 23 (stable release) runs with systemd v222. The Upcoming Release of Fedora 24 will have systemd v229 and should work.

**Comment by eworm-de** [comment]
Ah, did not know this option was introduced in `systemd` v227. Perhaps I should cut a release before that change. Anyway... I have some pending changes that will require (not yet released) `systemd` v230...

We had a mail conversation back in January. Though it still did not work for you. Did you have an intermediate version that worked for you? What commit?

**Comment by eworm-de** [comment]
I've released version 0.6.0 and 0.6.1. Use whatever fits your distribution.
