### ISSUE TITLE
[FEATURE REQUEST] Prompt for second factors instead of getting them on the command line

### ISSUE THREAD

**Issue by guiniol** [eworm-de/mkinitcpio-ykfde#8]
I don't really like having to type the 2FA on the command line, and would much rather have a prompt like when it asks for the encryption key (ie, where the password is not echoed).
I don't know if this is in the works, but if it isn't I'll take a look and try to add it myself, if that's ok.

**Comment by eworm-de** [comment]
This is on my TODO list, but I did not work on it, yet.

**Comment by guiniol** [comment]
Ok. I'll see what I can do then.

**Comment by eworm-de** [comment]
Implemented with 49200cf2e80f7d23d2a2717130486316a9e12698. Want to give it a try?

**Comment by guiniol** [comment]
That was fast!
Works well here.
I would suggest a confirmation for the new second factor and when using -S for the first time.

**Comment by eworm-de** [comment]
> I would suggest a confirmation for the new second factor

Done in 631b93a7d056b1d73b14993cd13c5bdc3b1785a6. Want to give it a try?

> and when using -S for the first time.

When parsing the command line I do not know whether or not this is the initialization. In 1c02924892b0ee0e325677351667bad799b7a254 I changed the documentation to use `-n` for initialization. `-s` (and `-S` without verification) still works, though.

**Comment by guiniol** [comment]
That makes sense: `-n` is the new value of 2fa, and `-s` is only needed if there is already a 2fa.
I'll try it Friday (no access to the computer until then).

**Comment by guiniol** [comment]
Works here. Nice!

**Comment by eworm-de** [comment]
Thanks for testing!
